define([], function() {
  return {
    "PropertyPaneDescription": "Settings",
    "SettingsGroupName": "Source settings",
    "SourceLibraryNameLable": "Library name",
    "PickSourceSiteLabel": "Select source site",
    "DisableCreateNewRecordLabel": "Disable create new record button",
    "UISettingsGroupName": "UI settings",
    "RecordsTabLabel": "Greetings tab label",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "ActiveSitesDropdownLabel": "Active sites",
    "OpenDialogButton": "Upload new recording",
    "NotificationUploadedSuccessfully": "Uploaded successfully.",
    "NotificationUploadedFailed": "Failed to upload your record to document library. Try again or contact administrator.",
    "NotificationEmptyRecordName": "Please, specify record name.",
    "RecordNameTextFieldLabel": "Enter record name",
    "RecordFormatDropdownLabel": "Select format",
    "NewRecordingDialogTitle": "New recording",
    "EditRecordingDialogTitle": "Edit recording",
    "StartRecordLabel": "Record",
    "RerecordLabel": "Re-record",
    "StopRecordLabel": "Finish",
    "PauseRecordLabel": "Pause",
    "ResueRecordLabel": "Resume",
    "SaveRecordLabel": "Save",
    "CancelRecordLabel": "Cancel",
    "TableRecordLabel": "Record",
    "TableModifiedLabel": "Modified",
    "RecordsTabLabel": "Greetings",
    "BusinessHoursLabel": "Update Business Hours",
    "BusinessHoursTabLabel": "Business hours",
    "BusinessHoursErrorLable": "Unable to load business hours",
    "BusinessHoursAllDayButtonLabel": "All day",
    "BusinessHoursClosedButtonLabel": "Closed",
    "BusinessHoursWorkhoursLabel": "9am - 5pm",
    "BusinessHoursUpdateChangesButtonLabel": "Update Changes",
    "BusinessHoursCancelButtonLabel": "Cancel",
    "SkillPerAgentTabLabel": "Skills",
    "SkillPerAgentTableSkillLabel": "Skill",
    "SkillPerAgentTableScoreLabel": "Score",
    "SkillPerAgentTableAgentLabel": "Agent",
    "SkillPerAgentTableNewUpload": "New",
    "NewSkillDialogTitle": "New skill per agent",
    "EditSkillDialogTitle": "Edit skill per agent",
    "SkillPerAgentAgentDropdownLabel": "Agent",
    "SkillPerAgentSkillDropdownLabel": "Skill",
    "SkillPerAgentScoreSliderLabel": "Score",
    "ShouldCheckSupervisorLabel": "Should check supervisor list",
    "UseEscalatedSecuritySettingsLabel": "Use escalated security"
  }
});
