define([], function() {
  return {
    "PropertyPaneDescription": "Settings",
    "SettingsGroupName": "Source settings",
    "SourceLibraryNameLable": "Library name",
    "PickSourceSiteLabel": "Select source site",
    "DisableCreateNewRecordLabel": "Disable create new record button",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "OpenDialogButton": "Upload new recording",
    "NotificationUploadedSuccessfully": "Uploaded successfully.",
    "NotificationUploadedFailed": "Failed to upload your record to document library. Try again or contact administrator.",
    "NotificationEmptyRecordName": "Please, specify record name.",
    "RecordNameTextFieldLabel": "Enter record name",
    "RecordFormatDropdownLabel": "Select format",
    "NewRecordingDialogTitle": "New recording",
    "EditRecordingDialogTitle": "Edit recording",
    "StartRecordLabel": "Record",
    "RerecordLabel": "Re-record",
    "StopRecordLabel": "Finish",
    "PauseRecordLabel": "Pause",
    "ResueRecordLabel": "Resume",
    "SaveRecordLabel": "Save",
    "CancelRecordLabel": "Cancel",
    "TableRecordLabel": "Record",
    "TableModifiedLabel": "Modified"
  }
});
